### ISSUE TITLE
Progress on new geo data

### ISSUE THREAD

**Issue by davidchiles** [Burning-Man-Earth/iBurn-Data#2]
Todo:

- [x] [Outline](http://bl.ocks.org/d/2f7a01def383d1d0b325)
    - [x] Fix Rod's Road glitch at 0deg
    - [x] Fix Corner glitch along 2:00 and 10:00
    - [x] Remove tiny triangles at Esplanade and 5:30/6:30
- [x] [Street centerlines](http://bl.ocks.org/anonymous/raw/7fa5ef259e4b67cf90bb/)
    - [x] Entrance Road
    - [x] Airport Road
    - [x] Depot Roads at 5:30 & 6:30
- [x] [Areas](http://bl.ocks.org/anonymous/raw/047d27fd7be31e0357b7/)
- [x] Cleanup js file and structure

**Comment by chrisballinger** [comment]
:+1: 

Did you see that email about making a geocoder that goes in the opposite direction inside the app? e.g. GPS -> Playa Address?

**Comment by davidchiles** [comment]
@chrisballinger Yeah interesting idea
